### ISSUE TITLE
triggering preview blanks vim until zathura is closed

### ISSUE THREAD

**Issue by hook-s3c** [lingnand/pandoc-preview.vim#1]
as titled

**Comment by varao** [comment]
I fixed this by changing line 42 in pandoc-preview.vim from
`call system(printf("%s %s",
                        \shellescape(g:pandoc_preview_pdf_cmd),
                        \pdf))`
to 
`call system(printf("%s %s &",
                        \shellescape(g:pandoc_preview_pdf_cmd),
                        \pdf))`
running your pdf-viewer in the background (else vim waits till it returns).

**Comment by lingnand** [comment]
Good to know! I don't use this anymore, but feel free to send a PR to me for this if you want.
